kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: strimzi-admin
  labels:
    app: strimzi
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkanodepools
      - kafkaconnects
      - kafkamirrormakers
      - kafkausers
      - kafkatopics
      - kafkabridges
      - kafkaconnectors
      - kafkamirrormaker2s
      - kafkarebalances
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkanodepools/scale
      - kafkaconnects/scale
      - kafkamirrormakers/scale
      - kafkabridges/scale
      - kafkaconnectors/scale
      - kafkamirrormaker2s/scale
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
    apiGroups:
      - core.strimzi.io
    resources:
      - strimzipodsets
